### PR TITLE
Flask_app_skeleton

### PR DESCRIPTION
**Pull request by Bsubs**
I've cleaned up the unecessary venv files and repushed the repo for review

### CODE REVIEW

**Comment by jwyatt1999** [comment]
I don't know what would happen if we merged this...

This deletes a bunch of files that have already been deleted when I reverted the original merge with the 500,00+ line changes.
It seems like this will probably just add a gitignore file??

Either way, I'm a little sus about what would happen and think it would be good to either pull main into this branch to see what happens, or create an entirely new PR that adds the .gitignore file

Edit: Upon looking at your branch I can see roughly what will happen. We definitely want to pull main onto this branch, that'll make it possible for me to actually review what exactly will be changing on main when we merge this.

**Comment by Bsubs** [comment]
I've pulled main into this branch and have updated the following:
1. All HTML files are now in /cartographers/templates
2. All javascript and CSS files are now in /cartographers/static

**Comment by jwyatt1999** [comment]
I think this looks fine. Let's merge this and see what happens. Worst come to worst we can revert it if something goes horribly wrong.

**Comment by jwyatt1999** [comment]
Also, this has a bunch of merge conflicts that will need to be resolved first, which is a bit curious given you pulled in main. Idk why that could be. The best way to resolve the merge conflicts will be to use the command `git pull origin main` in your VSCode terminal. Then use the command `git mergetool` and VSCode will go through file by file and ask what you want to keep/remove, after that is done you can just commit the changes (no message required) and it'll all be resolved :)

**Review by jwyatt1999 — APPROVED** [review]

**Comment by jwyatt1999** [comment]
Closing this PR because the important changes have been pulled out into a separate, cleaner branch: https://github.com/jwyatt1999/CITS3403_Cartographers/tree/JooKai_Flask_App

**Pull request closed without merging**
